### ISSUE TITLE
List on Marketplace and process transactions independently

### ISSUE THREAD

**Issue by vipulw2011** [Ercenk/ContosoAMPBasic#14]
Hi, I am developing a Saas application which I need to publish/list on appsource so that it can be used in Microsoft Teams. The Saas application has different licensing models/plans. I got the implementation flow doc when we make transaction via Microsoft itself. But I want to implement the purchase on my side. 
How will be the purchase flow for the end customer in this case ? 
How can I show plan listing on marketplace when using independent transaction ?
Do I need to tell Microsoft that this person has the license via some API ?

Thanks in advance.

**Comment by Ercenk** [comment]
Hello Vipul,
Consider taking this approach:
1. Publish a SaaS offer on Microsoft Commercial Marketplace
2. Implement a the code on your add in to call your API on your service to check whether the customer has purchased your solution, and prompt the customer to subscribe to your SaaS solution on AppSource or Azure Marketplace if you detect he/she is not subscribed 
3. Implement your landing page for the SaaS offer to onboard the customer using the method of your choice. E.g. you are required by policy to log the user on with AAD on the landing page, save the tenant ID and the user ID of the customer to your access control list and ask the user to login to Teams add in with that account, then call home on your API to check the access.
HTH...
