### ISSUE TITLE
Azure.Cosmos Error

### ISSUE THREAD

**Issue by CSharpQuestion** [Ercenk/ContosoAMPBasic#4]
I configured everything as described (all settings in appsettings.json for now) but am getting the following error when opening https://localhost:5001/ (with dotnet run). Any idea why this is happening?

ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
Microsoft.Azure.Cosmos.Table.CloudStorageAccount.Parse(string connectionString)

**Comment by desflan** [comment]
You need to set up a Storage account in Azure. Then in Startup.cs, the connection string for this storage account must be passed as a parameter to the existing method _WithAzureTableOperationsStore()_

`services.AddFulfillmentClient(options => this.configuration.Bind("FulfillmentClient", options))
  .WithAzureTableOperationsStore(<my-storage-account-connection-string>);`

**Comment by Ercenk** [comment]
Yes,correct. I fixed the readme, please check it out.
