### ISSUE TITLE
How to provision resources straight into the customer Azure Subscription?

### ISSUE THREAD

**Issue by dev-bre** [Ercenk/ContosoAMPBasic#7]
Hi,
I am trying to change the solution to provision resources straight into the customer Azure Subscription, like AppServices, Storage Accounts, etc.  Using ARM templates.

I am currently allowing customers to subscribe to a Software as a Service (SaaS) solution. 
Is it the right approach?
Any guidance on how to gain writing credentials on the customer subscription?

**Comment by scseely** [comment]
You may want to use an Azure Managed Application instead.

**Comment by Ercenk** [comment]
Please also take a look into how to use Azure Management APIs and Azure SDK for that.
