### ISSUE TITLE
Development during certification

### ISSUE THREAD

**Issue by nbarkhina** [Ercenk/ContosoAMPBasic#9]
Is there a way to create an Offer and start developing and testing the API's without publishing the app and waiting for that 2 day certification? Can you just create a Dev version of an offer to go through the sample or does it need to be a real Offer?

Thanks

**Comment by Ercenk** [comment]
You need to go through the certification process to be able to call the APIs on the marketplace side. Your API client is identified by the AAD tenant ID and App ID by the Marketplace by placing it on an ACL. The certification process puts it on the ACL.

**Comment by Ercenk** [comment]
As per https://github.com/Ercenk/ContosoAMPBasic/issues/9#issuecomment-600892914
